export const UPSTREAM_HTTP_CLIENT = Symbol("UPSTREAM_HTTP_CLIENT");
export const IDEMPOTENCY_STORE = Symbol("IDEMPOTENCY_STORE");
export const CHANNEL_DOMAIN_EVENTS_SINK = Symbol("CHANNEL_DOMAIN_EVENTS_SINK");
